export const languages: Record<string, string> = {
    ca: 'Català',
    cs: 'Čeština',
    en: 'English',
    es: 'Español',
    eu: 'Euskara',
    de: 'Deutsch',
    fr: 'Français',
    it: 'Italiano',
    nl: 'Nederlands',
    pl: 'Polski',
    'pt-BR': 'Português (Brasil)',
    tr: 'Türkçe',
    zh: '简体中文',
};
